import { Raleway } from 'next/font/google'
import './globals.css'

const raleway = Raleway({
  subsets: ['latin'],
  variable: ['--font-raleway'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} font-raleway bg-mobile bg-dark-blue xl:bg-desktop h-screen bg-cover bg-center bg-no-repeat`}
      >
        {children}
      </body>
    </html>
  )
}
